image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup database and run migrations
    init: |
      docker-compose up -d
      sleep 5
      bundle install
      rails db:create db:migrate
    command: echo "Ready!"

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public