default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: gitpod
  password: password
  pool: 5

development:
  <<: *default
  database: good_night_development

test:
  <<: *default
  database: good_night_test
